# Generated by Django 5.2.1 on 2025-11-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                ("titulo", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=100)),
                (
                    "data_publicacao",
                    models.DateField(verbose_name="data de publicação"),
                ),
                ("resumo", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
